name: "Fluxzero Deploy"
description: "Deploy an application to a Fluxzero cluster"
author: fluxzero-io
branding:
  icon: upload-cloud
  color: gray-dark

inputs:
  token:
    description: "A Fluxzero System API JWT"
    required: true
  cluster-name:
    description: "The name of the cluster to deploy the application to"
    required: true
  application-name:
    description: "The name of the application to deploy"
    required: true
  image-name:
    description: "The name of the docker image"
    required: true
  version:
    description: "The version/tag of the docker image"
    required: false
    default: "latest"
  deployment-endpoint:
    description: "The endpoint to use for deploying the application"
    required: false
    default: "https://api.dashboard.fluxzero.io/deploy-application"

runs:
  using: "node20"
  main: "dist/index.js"
